Repository anup2702/build-on-coffee, pull requests merged in 2025-10, with the labels that each got.

#399 Feat: Add Tailwind CSS quiz
  data/tailwindQuiz.js
  src/Component/Quiz.jsx
Labels: GSSoC'25, level2

#400 Feat: Add Next.js quiz
  data/nextjsQuiz.js
  src/Component/Quiz.jsx
Labels: GSSoC'25, level2

#420 feat: add cloud-native concepts quiz (#409)
  data/cloudNativeConcepts.js
  src/Component/Quiz.jsx
Labels: GSSoC'25, level3

#459 Add Design Patterns in JS & React Quiz (Resolves #430)
  data/designPatternsQuiz.js
  src/Component/Quiz.jsx
Labels: GSSoC'25, level2

#467 Revert "Revert "Update Readme""
  README.md
  src/assets/gssoc logo.png
Labels: enhancement, GSSoC'25, level1
